 language: node_js
 node_js:
   - "5.2"
   - "4.3"
   - "0.12"
   - "0.10"
 script:
   - "echo 'running script'"
   - "npm run build && npm run test && npm run cover"
 after_script:
   - "echo 'running after_script'"
   - "cat ./coverage/lcov.info | coveralls"

