 language: node_js
 node_js:
   - "0.10"
 before_install:
   - "echo 'running before_install'"
   - "npm install -g gulp istanbul"   
 script:
   - "echo 'running script'"
   - "npm test"
 after_script: 
   - "echo 'running after_script'"
   - "cat ./coverage/lcov.info | coveralls"

